name: Deploy to Wikipedia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/setup@main
        with:
          username: Xiplus
          botname: ${{ secrets.DEPLOY_XIPLUS_BOT_NAME }}
          password: ${{ secrets.DEPLOY_XIPLUS_BOT_PASS }}
          family: wikipedia
          mylang: zh

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/deploy@main
        with:
          src: dist/unblock-zh-helper.iife.js
          dst: User:Xiplus/js/unblock-zh-helper/unblock-zh-helper.iife.js
          summary: ${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}

      - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/deploy@main
        with:
          src: dist/style.css
          dst: User:Xiplus/js/unblock-zh-helper/style.css
          summary: ${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}

      - uses: xiplus-mediawiki-programs/deploy-mediawiki/.github/actions/deploy@main
        with:
          src: dist/load.js
          dst: User:Xiplus/js/unblock-zh-helper/load.js
          summary: ${{ steps.vars.outputs.sha_short }} ${{ github.event.head_commit.message }}
